name: "Release"

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*"
env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.1.app
  
jobs:
  release:
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Carthage
        run: ./carthage.sh bootstrap --no-use-binaries --use-xcframeworks --use-submodules --platform iOS
      - name: Build GoogleMaps
        run: ./make_xcframework.sh
      - name: Archive
        run: ./make_release.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Release/CHIPageControl.xcframework.zip
            Release/GoogleMapsBase.xcframework.zip
            Release/GoogleMapsM4B.xcframework.zip
            Release/SVProgressHUD.xcframework.zip
            Release/GoogleMaps.xcframework.zip
            Release/GoogleMapsCore.xcframework.zip
            Release/GooglePlaces.xcframework.zip
            Release/SlideMenuControllerSwift.xcframework.zip
